# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/git-pair/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X {{.Env.PROJECT}}/internal/diagnostics.Version={{.Version}} -X {{.Env.PROJECT}}/internal/diagnostics.Commit={{.Commit}} -X {{.Env.PROJECT}}/internal/diagnostics.BuildDate={{.Date}}
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
# aurs:
#   - name: git-pair-bin
#     description: 'A simple CLI app to make it easier for pairing for co-authoring commits.'
#     maintainers:
#       - 'Malachi Soord <me@malachisoord.com>'
#     homepage: 'https://github.com/inverse/git-pair/'
#     git_url: 'ssh://aur@aur.archlinux.org/git-pair-bin.git'
#     private_key: '{{ .Env.AUR_KEY }}'
#     license: 'MIT'
release:
  draft: true
  name_template: '{{.ProjectName}}-v{{.Version}}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
