version: '3'

vars:
  PROJECT: github.com/inverse/git-pair

tasks:
  build:
    desc: Build project
    deps: [clean]
    cmds:
      - PROJECT={{.PROJECT}} goreleaser build --single-target --snapshot --clean
    silent: true
  clean:
    desc: Clean project
    cmds:
      - go clean
      - rm -rf dist/*
    silent: true
  format:
    desc: Format code
    cmds:
      - gofmt -s -w .
    silent: true
  lint:
    desc: Lint code
    cmds:
      - golangci-lint run 
  goreleaser: 
    desc: Perform dev goreleaser
    deps: [clean]
    cmds:
      - PROJECT={{.PROJECT}} goreleaser release --snapshot --clean --skip-publish
