name: CI
on:
  push:
    branches:
      - master
  pull_request: ~
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Go version from .mise.toml
        uses: SebRollen/toml-action@v1.0.2
        id: get-golang-version
        with:
          file: .mise.toml
          field: tools.golang
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ steps.get-golang-version.outputs.value }}'
      - name: Get golangci-lint version from .mise.toml
        uses: SebRollen/toml-action@v1.0.2
        id: get-golangci-lint-version
        with:
          file: .mise.toml
          field: tools.golangci-lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v${{ steps.get-golangci-lint-version.outputs.value }}'
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
