name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Get Go version from .tool-versions
        run: echo "GO_VERSION=$(cat .tool-versions | grep -oP 'golang \K((\w+.)+\w+)')" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: Get goreleaser version from .tool-versions
        run: echo "GORELEASER_VERSION=$(cat .tool-versions | grep -oP 'goreleaser \K((\w+.)+\w+)')" >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: '${{ env.GORELEASER_VERSION }}'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PROJECT: github.com/inverse/git-pair
          AUR_KEY: ${{ secrets.AUR_KEY }}
