name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Get Golang version from .mise.toml
        uses: SebRollen/toml-action@v1.2.0
        id: get-golang-version
        with:
          file: .mise.toml
          field: tools.golang
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ steps.get-golang-version.outputs.value }}'
      - name: Get nfpm version from .mise.toml
        uses: SebRollen/toml-action@v1.2.0
        id: get-nfpm-version
        with:
          file: .mise.toml
          field: tools.nfpm
      - name: Setup nfpm
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://github.com/goreleaser/nfpm/releases/download/v${{ steps.get-nfpm-version.outputs.value }}/nfpm_${{ steps.get-nfpm-version.outputs.value }}_Linux_x86_64.tar.gz'
          name: 'nfpm'
          version: '${{ steps.get-nfpm-version.outputs.value }}'
      - name: Setup fury
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://github.com/gemfury/cli/releases/download/v0.20.1/fury_0.20.1_Linux_64bit.tar.gz'
          name: 'fury'
          version: '0.20.1'
      - name: Get goreleaser version from .mise.toml
        uses: SebRollen/toml-action@v1.2.0
        id: get-goreleaser-version
        with:
          file: .mise.toml
          field: tools.goreleaser
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '${{ steps.get-goreleaser-version.outputs.value }}'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PROJECT: github.com/inverse/git-pair
          AUR_KEY: ${{ secrets.AUR_KEY }}
      - name: Upload rpm and apt binaries
        run: ./scripts/deploy.sh
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
